# -*- coding: utf-8 -*-
require 'yaml'
require "colorize"
require 'command_line/global'

begin
  config = YAML.load(File.read(".hc_config.yaml"))
  p ['config', config]
rescue Errno::ENOENT
  config = {year: 2025,
lecture: "math_ex_ala",
source_html: "math_ex_ala_26s.html",
glob_extensions: "c*/*.html"
           }

  File.write(".hc_config.yaml",YAML.dump(config))
  puts "edit .hc_config.yaml"
  exit
end

$year = config[:year].to_s
$lecture = config[:lecture] #'math_ex_ala'
$source_html = config[:source_html]
$local_dir = File.join('~/Sites/new_ist/Lectures',$year)
$lec_dir = File.expand_path(File.join($local_dir,$lecture))
$glob_extensions = config[:glob_extensions].to_s

task :default do
  p ['$lec_dir', $lec_dir]
  p ['$lec_dir', $lec_dir]
  system "rake -T"
end

desc "mk new sub directory"
task :mk_new_sub_dir do
  stack_dir = '_mk_stack_dir'
  dir_name = 'new_sub_dir'
  ["mkdir #{dir_name}",
   "cp #{File.join(stack_dir,'theme.css')} .",
   "cp #{File.join(stack_dir,'style_top_link.css')} ./style.css",
   "cp #{File.join(stack_dir,'readme.org')} #{dir_name}",
   "cp #{File.join(stack_dir,'mk_stack_dir', 'mk_stack_dir.001.png')} #{dir_name}",
   "cp #{File.join(stack_dir,'style_w_link_button_one_column.css')} #{dir_name}"
  ].each do |comm|
    puts comm
    system comm
  end
end

desc "DIR : make DIR light table" #desc -> description
task :mk_light_table do # any name on task_name
  comm = "ruby _mk_stack_dir/auto_mk_light_table.rb"
  puts comm
  puts "\nFor making light table structured, modify light_table.yaml.".green
  exit
end

desc "auto generate top.html from light_table.yaml" #desc -> description
task :generate_html do # any name on task_name
  comm = "ruby _mk_stack_dir/generate_html.rb"
  puts comm
  puts "\nAfter light_table.yaml, auto generate ./#{$source_html}".green
  exit
end

desc "commit local dir" #desc -> description
task :commit do # any name on task_name
  system "mkdir #{$lec_dir}"
  Dir.glob($glob_extensions.split('/').first).each do |s_dir|
    p s_dir 
    next unless File.directory?(s_dir)
    
    # 除外したいディレクトリのリスト
    excludes = %w[.venv/ venv/ env/ .env/ __pycache__/ .git/]
    exclude_opts = excludes.map { |e| "--exclude=\"#{e}\"" }.join(" ")
    
    comm = "rsync -av #{exclude_opts} #{s_dir} #{$lec_dir}"
    p comm
    system comm
  end
  ["cp #{$source_html} #{$lec_dir}",
   "cp style.css theme.css #{$lec_dir}",
   "chmod -R a+r #{$lec_dir}"
  ].each do |comm|
    p comm
    system comm
  end
  exit
end

desc "push light tables to web server"
task :push do
  ist_dir = File.join("nishitani@ist.ksc.kwansei.ac.jp:~/public_html/Lectures/",
                         $year)
  https_file = File.join("https://ist.ksc.kwansei.ac.jp/~nishitani/Lectures",
                         $year, $lecture, $source_html)
  ["rsync -F -auvz -e ssh #{$lec_dir} #{ist_dir}",
   "open #{https_file}"].each do |comm|
    puts comm
    system comm
  end
end

desc "mk link from ligh_table.yaml"
task :mk_link do
  comm = "ruby c0_mk_stack_dir/mk_link.rb"
  puts comm
  puts "\nFor making links for up, prev, next buttons from light_table.yaml.".green
  exit
  
end
