# -*- coding: utf-8 -*-
require "colorize"
require 'command_line/global'

task :default do
  system "rake -T"
end

desc "auto convert" #desc -> description
task :conv do # any name on task_name
  # your code goes
  file = ARGV[1] || 'readme.org'
  p md_name = [File.basename(file, '.org'), 'md'].join('.')
  p html_name = [File.basename(file, '.org'), 'html'].join('.')
  ["pandoc #{file} --from=org --to=markdown --output=#{md_name}",
   "pandoc #{md_name} --from=markdown --to=html -s --css=style_w_link_button.css --output=#{html_name}"].each do |comm|
    puts comm
    system comm
  end
end

